//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SacredItemManager.rc
//
#define IDD_SACREDITEMMANAGER_DIALOG    102
#define IDD_ITEMPLACEMENTDISP_DIALOG    103
#define IDD_DUPEITEM_DIALOG             104
#define IDD_EDITITEM_DIALOG             105
#define IDD_EXPORTITEM_DIALOG           106
#define IDD_IMPORTITEM_DIALOG           107
#define IDD_UNSLOTITEM_DIALOG           108
#define IDD_ITEMEDITHELPER_DIALOG       109
#define IDD_ABOUT_DIALOG                110
#define IDD_VIEWDUMP_DIALOG             111
#define IDD_VIEWITEM_DIALOG             112
#define IDD_EDITID_DIALOG               113
#define IDR_MAINFRAME                   128
#define IDR_MENU_EDITITEM_COPY_POPUP    132
#define IDD_DIALOG_PICBROWSE            133
#define IDD_DIALOG_SITBROWSE            134
#define IDI_ICON_ITEM                   138
#define IDR_MENU_VIEWITEM_COPY_POPUP    139
#define IDC_TREE_ITEMS                  1000
#define IDC_STATIC_FRAME_CURRENT_HERO   1001
#define IDC_EDIT_CURRENT_HERO           1002
#define IDC_BUTTON_BROWSE_CURRENT_HERO  1003
#define IDC_BUTTON_CLOSE_CURRENT_HERO   1004
#define IDC_BUTTON_RELOAD_CURRENT_HERO  1005
#define IDC_BUTTON_SAVE_CURRENT_HERO    1006
#define IDC_STATIC_FRAME_ITEM_ACTIONS   1007
#define IDC_BUTTON_PLACEMENT            1008
#define IDC_BUTTON_DELETEITEM           1009
#define IDC_BUTTON_EXPORT_ITEM          1010
#define IDC_BUTTON_DUPLICATE_ITEM       1011
#define IDC_BUTTON_UNSLOT_ITEM          1012
#define IDC_BUTTON_IMPORT_ITEM          1013
#define IDC_BUTTON_SHRINKITEM           1014
#define IDC_BUTTON_EDIT_ITEM            1015
#define IDC_STATIC_FRAME_MISC           1017
#define IDC_BUTTON_ABOUT                1018
#define IDC_PLACEMENT_CHEST             1020
#define IDC_PLACEMENT_BACKPACK          1021
#define IDC_EDIT_DUPE_TOTAL             1023
#define IDC_SPIN_DUPETOTAL              1024
#define IDC_CHECK_SHRINK                1025
#define IDC_CHECK_INC_SLOTTED_ITEMS     1026
#define IDC_COMBO_DUPETO                1027
#define IDC_STATIC_FRAME_HMT            1030
#define IDC_STATIC_TOTAL_ITEMS          1031
#define IDC_BUTTON_HELP                 1032
#define IDC_HEX_EDIT_CTRL               1033
#define IDC_LIST_TRANSLATIONS           1034
#define IDC_CHECK_DECIMAL_DATA_VIEW     1036
#define IDC_COMBO_BYTEORDER             1037
#define IDC_BUTTON_RESET_BUFFER         1040
#define IDC_STATIC_FNT                  1041
#define IDC_EDIT_EX_ITEMID              1043
#define IDC_EDIT_EX_ITEMNAME            1044
#define IDC_EDIT_EX_ITEMAUTH            1045
#define IDC_EDIT_EX_ITEMDESC            1046
#define IDC_CHECK_EX_INCSLOT            1047
#define IDC_STATIC_EX_ITEMPIC           1050
#define IDC_CHECK_SHOW                  1051
#define IDC_STATIC_IMGV                 1052
#define IDC_STATIC_IMG                  1053
#define IDC_STATIC_INVSIZEZ             1054
#define IDC_BUTTON_VIEWDUMP             1055
#define IDC_EDIT_IDZ                    1056
#define IDC_EDIT_NAMEZ                  1057
#define IDC_EDIT_DESCR                  1058
#define IDC_STATIC_ITIFR                1058
#define IDC_EDIT_AUTHZ                  1059
#define IDC_EDIT_ITEM_TO_IMPORT         1059
#define IDC_BUTTON_BROWSEIMPORTITEM     1060
#define IDC_EDIT_MINLVLZ                1060
#define IDC_COMBO_IMPORTITEM_TO         1061
#define IDC_EDIT_LVLZ                   1061
#define IDC_CHECK_SHRINK_IMPORT         1064
#define IDC_COMBO_UNSLOTTO              1067
#define IDC_BUTTON_HELPER               1068
#define IDC_EDIT_ATTR_VALUE             1069
#define IDC_COMBO_ITEM_ATTRS            1070
#define IDC_EDIT_ATTR_ID                1071
#define IDC_RADIO_ATTR_TEXT             1072
#define IDC_RADIO_ATTR_NUM              1073
#define IDC_COMBO_SLOTS                 1112
#define IDC_RADIO_SLOT_NONE             1113
#define IDC_RADIO_SLOT_BRONZE           1114
#define IDC_RADIO_SLOT_SILVER           1115
#define IDC_RADIO_SLOT_GOLD             1116
#define IDC_RADIO_SLOT_GREEN            1117
#define IDC_RADIO_SLOT_PLAT             1118
#define IDC_COMBO_ATTRIBUTE             1122
#define IDC_BUTTON_RELOADATTRDB         1124
#define IDC_BUTTON_EDITATTRDB           1125
#define IDC_BUTTON_APPLY_ATTR_CHANGE    1126
#define IDC_STATIC_ABOUT                1127
#define IDC_BUTTON_GOTO                 1129
#define IDC_SPIN_ATTR                   1130
#define IDC_HEXEDIT_VIEW                1131
#define IDC_STATIC_VI_PICTURE           1132
#define IDC_EDIT_VI_DESCID              1133
#define IDC_EDIT_VI_NAME                1134
#define IDC_EDIT_VI_ITEMDESC            1135
#define IDC_EDIT_VI_AUTHOR              1136
#define IDC_STATIC_VI_INVSIZE           1138
#define IDC_BUTTON_VI_VIEWDUMP          1139
#define IDC_LIST_VI_ATTRLIST            1140
#define IDC_EDIT_VI_MINLVL              1141
#define IDC_EDIT_VI_LVL                 1142
#define IDC_STATIC_VI_FRAMEATTRS        1143
#define IDC_BUTTON_VIEWITEM             1144
#define IDC_BUTTON_EDIT_DESC_ID         1145
#define IDC_EDIT_OLDID                  1146
#define IDC_EDIT_NEWID                  1147
#define IDC_BUTTON_WTFCID               1150
#define IDC_EDIT_RESIST_FIRE            1152
#define IDC_CHECK_CR_SERA               1153
#define IDC_EDIT_RESIST_MAGIC           1158
#define IDC_EDIT_RESIST_POISON          1159
#define IDC_EDIT_RESIST_PHYSICAL        1160
#define IDC_EDIT_DAMAGE_FIRE_FROM       1161
#define IDC_EDIT_DAMAGE_FIRE_TO         1162
#define IDC_EDIT_DAMAGE_MAGIC_FROM      1163
#define IDC_EDIT_DAMAGE_MAGIC_TO        1164
#define IDC_EDIT_DAMAGE_POISON_FROM     1165
#define IDC_EDIT_DAMAGE_POISON_TO       1166
#define IDC_EDIT_DAMAGE_PHYSICAL_FROM   1167
#define IDC_EDIT_DAMAGE_PHYSICAL_TO     1168
#define IDC_EDIT_IATTACK                1169
#define IDC_EDIT_IDEFENSE               1170
#define IDC_EDIT_ILEVEL                 1171
#define IDC_EDIT_IMINLEVEL              1172
#define IDC_CHECK_CR_GLADI              1173
#define IDC_CHECK_CR_BM                 1174
#define IDC_CHECK_CR_DE                 1175
#define IDC_CHECK_CR_WE                 1176
#define IDC_CHECK_CR_VAMP               1177
#define IDM_EDITITEM_COPY               32771
#define ID_POPUP_COPY                   32772

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        140
#define _APS_NEXT_COMMAND_VALUE         32773
#define _APS_NEXT_CONTROL_VALUE         1156
#define _APS_NEXT_SYMED_VALUE           114
#endif
#endif
